# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_cachetable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cachetable',
            table='Cache_Table',
        ),
    ]
