# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_auto_20200927_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachetable',
            options={'managed': False},
        ),
    ]
