# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-27 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_delete_cachetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_lable', models.CharField(max_length=200)),
                ('cache_content', models.TextField()),
            ],
            options={
                'db_table': 'Cache_Table',
            },
        ),
    ]
