# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_auto_20200928_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.IntegerField()),
                ('follow_date', models.DateField()),
                ('price_at_follow_time', models.FloatField()),
                ('follow_comment', models.TextField()),
            ],
            options={
                'db_table': 'Follow_Table',
                'managed': False,
            },
        ),
    ]
